### ISSUE TITLE
جواب سوالات به زبان سی‌شارپ

### ISSUE THREAD

**Issue by HamidMolareza** [erfanghorbanee/quera-answers#1]
سلام
منم جواب سوالاتی (که به مرور) حل میکنم رو توی این [مخزن](https://github.com/HamidMolareza/QueraProblems) قرار میدم.

[مخزن شما](https://github.com/HamidMolareza/QueraProblems#related) رو هم اضافه کردم.

زبون اصلی سی‌شارپ هستش. اگر کسی لازم داشت لطفا بهش معرفی کنید.

ممنون.

**Comment by erfanghorbanee** [comment]
سلام وقت بخیر
ریپازیتوریتون رو بررسی کردم خیلی تمیز بود.
حتما

موفق باشید.
